### ISSUE TITLE
FreeRTOS SMP

### ISSUE THREAD

**Issue by bob1414** [chipsalliance/riscv-fw-infrastructure#1]
Hello, Our group used the FPGA-based SweRV EH2 core in a project, and wanted to use FreeRTOS SMP on it to make full use of the cores.

But the freertos and rtosal in WD-FW do not seem to  support SMP. Is there any RTOS adaptation based on the SMP version?

**Comment by oferShinaar** [comment]
Hi Bob,
We have FreeRTOS SMP branch but it is not in the mainstream.
We can port it to the mainstream if it is something you want to use. Keep in mind that FreeRTOS SMP is still in WIP mode on Amazon.

Ofer

**Comment by bob1414** [comment]
> 
> 
> Hi Bob, We have FreeRTOS SMP branch but it is not in the mainstream. We can port it to the mainstream if it is something you want to use. Keep in mind that FreeRTOS SMP is still in WIP mode on Amazon.
> 
> Ofer

Hi Ofer, 
Thanks for your reply and reminder . If possible, hope you can port it.
We just want to use FreeRTOS SMP to test dual-core, and the simulation based on whisper also makes debugging easy for us.

Bob

**Comment by nati-rapaport** [comment]
Hi Bob,
I'm working on porting FreeRTOS SMP to master branch (subject to priority with other tasks..)
Will update you when it is done
Nati

**Comment by oferShinaar** [comment]
issue #1 will be closed once SMP migration will be complete

**Comment by oferShinaar** [comment]
@bob1414 we added a **static/branch** for FreeRTOS-SMP. 
Please check it out. I have updated the readme with a note for "quick how to build and run"
 
[static/freertos-kernel-smp](https://github.com/chipsalliance/riscv-fw-infrastructure/tree/static/freertos-kernel-smp)
