### ISSUE TITLE
The Demo_multi_harts had invalid timer settings on the emulator wisper

### ISSUE THREAD

**Issue by bob1414** [chipsalliance/riscv-fw-infrastructure#2]
### Introduction
Hello, I want to run eth2  demo_multi_harts on the emulator wisper, and I encounter the problem of invalid timer settings.

### Test environment
Operating system：Ubuntu16.04
Riscv-fw-infrastructure ：The latest version

### Revise
Modified  `demo_multi_harts.c`
`#define D_DEMO_TIMER_PERIOD_MSEC_HART0           10000`
`#define D_DEMO_TIMER_PERIOD_MSEC_HART1           7500`
`#define D_DEMO_NUMBER_OF_TIMER_INTERRUPTS_HART0  200`
`#define D_DEMO_NUMBER_OF_TIMER_INTERRUPTS_HART1  300`

Only run `Part 4: Timer interrupts over 2 harts`

### Expected behavior
A timer interrupt is generated every 10s and 7.5s

### Observed/Actual behavior
The entire simulation program runs within 5s.
Fast timer interrupt, much less than 10s or 7.5s，

![1](https://user-images.githubusercontent.com/49646296/141439113-abc38f69-e699-41c9-b836-f1b3fe3ba576.png)

### Other
After many tests, it seems to be
`pspMachineTimerCounterSetupAndRun(M_DEMO_MSEC_TO_CYCLES(D_DEMO_TIMER_PERIOD_MSEC_HART1))`
for MachineTimer setting is invalid. 

But in Eth2 `demo_rtosal.c` ,  MachineTimer setting is normal, through
` #define D_MAIN_SOFTWARE_TIMER_PERIOD_TICKS 10000/D_TICK_TIME_MS`
It can reach 10s timer interrupt simulation.

Thanks for looking into the Problem. 
:D

**Comment by pasha-tikhonov** [comment]
Hi Bob,

Thank you for bringing our attention to this issue.

While I could not reproduce the behavior you report, there is indeed an issue with using whisper for demonstrating machine timer usage. Whisper is an ISS (instruction set simulator), so it is problematic to use it for showing "SoC services" (e.g.: machine timer, external interrupts,...). In simple words, machine-timer does not work on whisper and machine-timer part of multi-hart demo is not representative in this case. So if you need a reliable machine timer, you should use one of the supported boards (hifive or nexys).

On the other hand, if you only want to use the machine timer as a periodic "trigger", there is --alarm whisper flag (machine timer ISR is called every N msec, see whisper's help for more information).

I hope it helps. :-)

Pasha
